apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: vault-infra
  namespace: external-secrets
  annotations:
    argo-cd.argoproj.io/sync-wave: "1"
spec:
  provider:
    vault:
      server: "https://se.kms.teliacompany.net/"
      version: "v2"
      path: "infra"
      namespace: "Hid100007639/dwhs/"
      auth:
        appRole:
          path: "approle"
          roleId: "7b6dc3c2-7386-6e2c-1d38-e1ac6b0bfa06"
          secretRef:
            name: se.kms.teliacompany.net
            namespace: external-secrets
            key: secret_id