apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-auth-role
rules:
  - apiGroups: [""]
    resources: ["secrets", "serviceaccounts"]
    verbs: ["get", "create", "update", "delete"]
  - apiGroups: ["authentication.k8s.io"]
    resources: ["tokenreviews"]
    verbs: ["create"]