---
- name: Install and setup k3s on server nodes
  hosts: servers
  become: true
  vars_files:
    - secrets.yaml
  tasks:

    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
        state: present

    - name: Download and install k3s
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
      environment:
        INSTALL_K3S_EXEC: "--disable traefik"
        K3S_TOKEN: "{{ k3s_token }}"
        K3S_KUBECONFIG_MODE: "644"

    - name: Verify k3s installation
      command: k3s --version
      register: k3s_version

    - name: Display k3s version
      debug:
        msg: "Installed k3s version: {{ k3s_version.stdout }}"

    - name: Ensure k3s service is enabled and running
      systemd:
        name: k3s
        enabled: yes
        state: started

    - name: Check k3s cluster status
      command: kubectl get nodes
      register: cluster_status

    - name: Display k3s cluster status
      debug:
        msg: "K3s cluster status:\n{{ cluster_status.stdout }}"
