---
- name: Setup k3s agents
  hosts: agents
  become: true
  vars_files:
    - secrets.yaml
  tasks:

    - name: Get private_ip of the first server in the inventory
      set_fact:
        k3s_url: "https://{{ hostvars[groups['servers'][0]].private_ip }}:6443"

    - name: Ensure dependencies are installed
      apt:
        name:
          - curl
        state: present

    - name: Download and install k3s agent
      shell: |
        curl -sfL https://get.k3s.io | sh -
      args:
        executable: /bin/bash
      environment:
        K3S_URL: "{{ k3s_url }}"
        K3S_TOKEN: "{{ k3s_token }}"

    - name: Verify k3s agent installation
      command: k3s-agent --version
      register: agent_version

    - name: Display k3s agent version
      debug:
        msg: "Installed k3s agent version: {{ agent_version.stdout }}"

    - name: Ensure k3s-agent service is enabled and running
      systemd:
        name: k3s-agent
        enabled: yes
        state: started
