#cloud-config
packages:
  - curl
users:
  - name: admin
    ssh-authorized-keys:
      - ${admin_public_ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
  - name: ansible
    ssh-authorized-keys:
      - ${ansible_public_ssh_key}
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
runcmd:
  - apt-get update -y
  - curl https://get.k3s.io | INSTALL_K3S_EXEC="--disable traefik" K3S_TOKEN="${k3s_token}" K3S_KUBECONFIG_MODE="644" sh -