apiVersion: v2
name: metallb
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "v0.14.9"
dependencies:
  - name: metallb
    version: 0.14.9
    repository: https://metallb.github.io/metallb